import Link from 'next/link';
import { Icon, StatusBadge } from './Visuals';

export function ProductPreview() {
  return <div className="lp-product-preview" aria-label="Demonstração visual do fluxo de conteúdo"><div className="lp-preview-glow" /><div className="lp-preview-top"><div><span className="lp-preview-kicker">Workspace ativo</span><strong>Marca Aurora</strong></div><span className="lp-online"><i />Fluxo ativo</span></div><div className="lp-preview-body"><aside className="lp-preview-sidebar"><span className="active"><Icon name="dashboard" size={16} /></span><span><Icon name="content" size={16} /></span><span><Icon name="team" size={16} /></span><span><Icon name="gear" size={16} /></span></aside><div className="lp-preview-canvas"><div className="lp-preview-heading"><div><small>Solicitação #024</small><strong>Campanha de lançamento</strong></div><StatusBadge status="DRAFT" /></div><div className="lp-brief-card"><div className="lp-card-label"><Icon name="brief" size={14} />Briefing</div><p>Apresente a nova coleção com uma mensagem confiante, próxima e orientada a descoberta.</p><div className="lp-brief-meta"><span>Instagram Feed</span><span>Tom inspirador</span></div></div><div className="lp-preview-lower"><div className="lp-post-card"><div className="lp-post-image"><Icon name="sparkles" size={25} /><span>Nova coleção</span></div><p><strong>Uma nova estação começa aqui.</strong><br />Design para acompanhar seus próximos movimentos.</p></div><div className="lp-flow-card"><span>Fluxo de produção</span><div><i className="done"><Icon name="check" size={11} /></i><p><strong>Briefing recebido</strong><small>Contexto organizado</small></p></div><div><i className="current"><Icon name="edit" size={11} /></i><p><strong>Em revisão</strong><small>Aguardando equipe</small></p></div><div><i><Icon name="clock" size={11} /></i><p><strong>Aprovação</strong><small>Próxima etapa</small></p></div></div></div></div></div><div className="lp-floating-status"><Icon name="check" size={15} /><span><strong>READY</strong> Conteúdo pronto para revisar</span></div></div>;
}

export function HeroSection() {
  return <section className="lp-hero"><div className="lp-container lp-hero-grid"><div className="lp-hero-copy"><div className="lp-pill"><span /><Icon name="content" size={14} />Conteúdo organizado do briefing à aprovação</div><h1>Do briefing à publicação, <em>tudo em um só fluxo.</em></h1><p>Crie conteúdos para redes sociais, revise com sua equipe e mantenha sua marca ativa sem depender de processos manuais.</p><div className="lp-hero-actions"><Link href="/cadastro" className="button button-primary">Começar agora <Icon name="arrow-right" size={17} /></Link><a href="#como-funciona" className="button button-secondary"><Icon name="layout" size={17} />Ver como funciona</a></div><div className="lp-hero-note"><span><Icon name="check" size={14} />Comece com um workspace</span><span><Icon name="check" size={14} />Sem instalação</span><span><Icon name="check" size={14} />Ambiente local disponível</span></div></div><ProductPreview /></div></section>;
}

const benefits = [['brief', 'Menos tarefas manuais'], ['content', 'Conteúdo organizado'], ['check', 'Aprovação centralizada'], ['workspace', 'Gestão por marca'], ['archive', 'Histórico seguro'], ['sparkles', 'Preparado para automações futuras']] as const;
export function BenefitsStrip() {
  return <section className="lp-benefits-strip" aria-label="Benefícios principais"><div className="lp-container">{benefits.map(([icon, label]) => <div key={label}><Icon name={icon} size={16} /><span>{label}</span></div>)}</div></section>;
}
